name: hive_managed_example
description: Sample application for HiveManaged
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  hive_managed:
    path: ..
