name: madob
description: Madob is a super simple and easy to use highly-asynchronous library for database-synchronized objects. It is built upon hive, the blazing-fast key-value database.
version: 0.1.2
homepage: https://github.com/FaFre/madob

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  hive: ^1.3.0
  uuid: ^2.0.4

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  mockito: ^4.1.1
  hive_generator: ^0.7.0
  build_runner: ^1.7.2
  effective_dart: ^1.2.1
  madob_example:
    path: example
  madob_generator: ^0.2.3
