builders:
  madob_generator:
    import: "package:madob_generator/madob_generator.dart"
    builder_factories: ["getMadobGenerator"]
    build_extensions: { ".dart": [".g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
