name: madob_generator
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  effective_dart: ^1.2.1
  hive: ^1.4.0+1
  madob: ^0.1.0
  code_builder: ^3.2.1
  dart_style: ^1.3.3

dependencies:
  analyzer: ^0.39.4
  source_gen: ^0.9.4+7
  build: ^1.2.2
