name: madob_example
description: Sample application for Madob
version: 0.2.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  madob: ^0.1.1
  path: ^1.6.4

dev_dependencies:
  effective_dart: ^1.2.1
  madob_generator: ^0.2.3
  build_runner: ^1.7.4

dependency_overrides:
  madob:
    path: ..
  madob_generator:
    path: ../../madob_generator
