name: Dart CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies for 'madob'
        working-directory: madob
        run: pub get
      - name: Run tests for 'madob'
        working-directory: madob
        run: pub run test

  package-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: axel-op/dart-package-analyzer@stable
        id: madob_analysis # set an id for the current step
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: madob/

      - uses: axel-op/dart-package-analyzer@stable
        id: madob_generator_analysis # set an id for the current step
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: madob_generator/

      - name: Checking scores for 'madob'
        run: |
          MAINTENANCE_SCORE=${{ steps.madob_analysis.outputs.maintenance }}
          HEALTH_SCORE=${{ steps.madob_analysis.outputs.health }}
          if (( $(echo "$MAINTENANCE_SCORE < 100" | bc) )) || (( $(echo "$HEALTH_SCORE < 100" | bc) ))
          then
            exit 1
          fi
          
      - name: Checking scores for 'madob_generator'
        run: |
          MAINTENANCE_SCORE=${{ steps.madob_generator_analysis.outputs.maintenance }}
          HEALTH_SCORE=${{ steps.madob_generator_analysis.outputs.health }}
          if (( $(echo "$MAINTENANCE_SCORE < 100" | bc) )) || (( $(echo "$HEALTH_SCORE < 100" | bc) ))
          then
            exit 1
          fi
